name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
                        'Hello @${{ github.actor }} , thank you for submitting an issue to ArabR'
                         <a href="https://www.freeiconspng.com/img/33285">welcome png images</a>
                        :tada: Welcome to ArabR :tada:
                        "أهلا بكم في عرب آر"
                        "We're really excited to have your input into the project! :sparkling_heart:"
                         If you haven't done so already, please make sure you check out our [Contributing Guidelines](https://github.com/ArabR/ArabR-Website/blob/main/CONTRIBUTING.md).
        
        pr-message: 'Hello @${{ github.actor }} , thank you submitting a pull request to ArabR'
