name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
                         Hello @${{ github.actor }} , thank you for submitting an issue to ArabR!
                          You are awesome! 🤗
                          "أهلا بكم في عرب آر"
                         We're really excited to have your input into the project!
                         If you haven't done so already, please make sure you check out our Contributing Guidelines.
        
        pr-message: |
                          Thanks for opening this pull request!
                           You are awesome! 🤗
                            The ArabR community  really appreciates your time and effort to contribute to the project.
                              If you haven't done so already, please make sure you check out our Contributing Guidelines.

